import { useState, useEffect } from 'react';
// this code generated by Figma and gemini
export function NavDropdown({ options, defaultOption, onChange }) {
  // Initialize state: if no defaultOption is provided, fall back to the first option
  const [selectedOption, setSelectedOption] = useState(defaultOption || options[0]);
  const [isOpen, setIsOpen] = useState(false);
  useEffect(() => {
    if (defaultOption) {
      setSelectedOption(defaultOption);
    }
  }, [defaultOption]);
  // Logic to determine the "inactive" option
  const otherOption = selectedOption === options[0] ? options[1] : options[0];

  const handleOptionClick = (option) => {
  setSelectedOption(option);
  setIsOpen(false);
  
  if (onChange) {
    onChange(option);
  }
};

  const getBackgroundColor = (option) => {
    return option === options[0] ? '!bg-yellow-500' : '!bg-white-600';
  };

  const getHoverColor = (option) => {
    return option === options[0] ? 'hover:bg-yellow-600' : 'hover:bg-blue-700';
  };
  

  return (
    <div 
      className="relative"
      onMouseEnter={() => setIsOpen(true)}
      onMouseLeave={() => setIsOpen(false)}
    >
      <button
  type="button"
  className={`
    px-3 py-1.5 text-sm font-medium text-white rounded-full 
    transition-all flex items-center justify-center gap-2 
    min-w-[150px] shadow-sm border border-white/10
    ${getBackgroundColor(selectedOption)} 
    ${getHoverColor(selectedOption)}
  `}
  onClick={() => setIsOpen(!isOpen)}
>
  {/* The Gym Name */}
  <span>{selectedOption}</span>

  {/* The Small Downward Arrow */}
  <span className={`flex items-center transition-transform duration-200 ${isOpen ? 'rotate-180' : 'rotate-0'}`}>
    <svg 
      width="10" 
      height="10" 
      viewBox="0 0 24 24" 
      fill="none" 
      stroke="currentColor" 
      strokeWidth="4"   /* Slightly thicker for better visibility at 10px */
      strokeLinecap="round" 
      strokeLinejoin="round"
    >
      {/* This path creates a 'V' shape (pointing down) */}
      <path d="M6 9l6 6 6-6" />
    </svg>
  </span>
</button>
      
      {isOpen && (
        <div className="absolute top-full left-0 w-full mt-1 rounded-md shadow-lg overflow-hidden z-10">
          <button
            type="button"
            className={`w-full px-4 py-2 text-left text-white transition-colors ${getBackgroundColor(otherOption)} ${getHoverColor(otherOption)}`}
            onClick={() => handleOptionClick(otherOption)}
          >
            {otherOption}
          </button>
        </div>
      )}
    </div>
  );
}

export default NavDropdown;