import { useState } from 'react';
// this code generated by Figma and gemini
export function NavDropdown({ options, defaultOption, onChange }) {
  // Initialize state: if no defaultOption is provided, fall back to the first option
  const [selectedOption, setSelectedOption] = useState(defaultOption || options[0]);
  const [isOpen, setIsOpen] = useState(false);

  // Logic to determine the "inactive" option
  const otherOption = selectedOption === options[0] ? options[1] : options[0];

  const handleOptionClick = (option) => {
    setSelectedOption(option);
    setIsOpen(false);
  };

  const getBackgroundColor = (option) => {
    return option === options[0] ? '!bg-yellow-500' : '!bg-white-600';
  };

  const getHoverColor = (option) => {
    return option === options[0] ? 'hover:bg-yellow-600' : 'hover:bg-blue-700';
  };

  return (
    <div 
      className="relative"
      onMouseEnter={() => setIsOpen(true)}
      onMouseLeave={() => setIsOpen(false)}
    >
      <button
        type="button"
        className={`px-4 py-2 text-white rounded-md transition-colors flex items-center gap-2 min-w-[180px] justify-between ${getBackgroundColor(selectedOption)} ${getHoverColor(selectedOption)}`}
        onClick={() => setIsOpen(!isOpen)}
      >
        <span>{selectedOption}</span>
        <svg 
          className={`w-4 h-4 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none" 
          stroke="currentColor" 
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      
      {isOpen && (
        <div className="absolute top-full left-0 w-full mt-1 rounded-md shadow-lg overflow-hidden z-10">
          <button
            type="button"
            className={`w-full px-4 py-2 text-left text-white transition-colors ${getBackgroundColor(otherOption)} ${getHoverColor(otherOption)}`}
            onClick={() => handleOptionClick(otherOption)}
          >
            {otherOption}
          </button>
        </div>
      )}
    </div>
  );
}

export default NavDropdown;